import { Category, Merchant, Product, DemandSignal, StockoutRequest, RFQInquiry, Reservation } from '../types';
import { generateFreshnessHashSync } from '../utils/crypto';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'cat_hardware',
    name: 'Hardware & Construction',
    slug: 'hardware-construction',
    icon: 'Hammer',
    description: 'Cement, rebar, power tools, electrical wiring, plumbing, and structural supplies'
  },
  {
    id: 'cat_pharmacy',
    name: 'Medical & Healthcare',
    slug: 'medical-healthcare',
    icon: 'Activity',
    description: 'Prescription pharmaceuticals, emergency first aid, medical kits, and diagnostics'
  },
  {
    id: 'cat_agriculture',
    name: 'Farm Produce & Agri',
    slug: 'farm-produce-agri',
    icon: 'Wheat',
    description: 'Farm-fresh organic vegetables, grains, seeds, dairy, and local farmer supplies'
  },
  {
    id: 'cat_electronics',
    name: 'Electronics & Repair',
    slug: 'electronics-repair',
    icon: 'Cpu',
    description: 'Semiconductor chips, replacement parts, solder tools, batteries, and repair modules'
  },
  {
    id: 'cat_wholesale',
    name: 'Wholesale & FMCG',
    slug: 'wholesale-fmcg',
    icon: 'Boxes',
    description: 'Bulk provisions, staples, packaging, hotel/restaurant supplies with MOQ tiers'
  }
];

export const INITIAL_MERCHANTS: Merchant[] = [
  {
    id: 'merch_pioneer_hardware',
    businessName: 'Pioneer Construction & Hardware Depot',
    businessRegistrationNo: 'NP-VAT-601928471',
    category: 'Hardware & Construction',
    description: 'ISO-certified building material supplier and authorized structural distributor since 2008.',
    trustScore: 98.4,
    verificationStatus: 'verified',
    verifiedAt: '2026-08-15T10:00:00Z',
    contactPhone: '+977-1-5539201',
    contactEmail: 'orders@pioneerhardware.np',
    website: 'https://pioneerhardware.np',
    address: 'Kumaripati Main Road, Lalitpur',
    city: 'Lalitpur',
    state: 'Bagmati',
    latitude: 27.6715,
    longitude: 85.3180,
    rating: 4.9,
    reviewCount: 88,
    freshnessGuaranteeHours: 4,
    lastInventoryUpdate: new Date(Date.now() - 15 * 60000).toISOString(),
    branches: [
      {
        id: 'branch_pioneer_main',
        merchantId: 'merch_pioneer_hardware',
        branchName: 'Lalitpur Central Yard',
        address: 'Kumaripati Main Road, Lalitpur',
        city: 'Lalitpur',
        latitude: 27.6715,
        longitude: 85.3180,
        phone: '+977-1-5539201',
        isMain: true,
        operatingHours: '07:30 AM - 07:00 PM'
      },
      {
        id: 'branch_pioneer_balkhu',
        merchantId: 'merch_pioneer_hardware',
        branchName: 'Balkhu Ring Road Warehouse',
        address: 'Balkhu Chowk, Kathmandu',
        city: 'Kathmandu',
        latitude: 27.6842,
        longitude: 85.2980,
        phone: '+977-1-4289011',
        isMain: false,
        operatingHours: '08:00 AM - 06:30 PM'
      }
    ]
  },
  {
    id: 'merch_himalayan_organic',
    businessName: 'Himalayan Organic Harvest Cooperative',
    businessRegistrationNo: 'NP-COOP-882310',
    category: 'Farm Produce & Agri',
    description: 'Direct-from-farm certified organic produce, raw mountain honey, and artisanal dairy.',
    trustScore: 96.8,
    verificationStatus: 'verified',
    verifiedAt: '2026-07-20T09:30:00Z',
    contactPhone: '+977-1-4412099',
    contactEmail: 'supply@himalayanorganic.org',
    address: 'Lazimpat Embassy Corridor, Kathmandu',
    city: 'Kathmandu',
    state: 'Bagmati',
    latitude: 27.7240,
    longitude: 85.3210,
    rating: 4.8,
    reviewCount: 142,
    freshnessGuaranteeHours: 2,
    lastInventoryUpdate: new Date(Date.now() - 8 * 60000).toISOString(),
    branches: [
      {
        id: 'branch_himalayan_lazimpat',
        merchantId: 'merch_himalayan_organic',
        branchName: 'Lazimpat Flagship Store',
        address: 'Lazimpat Embassy Corridor, Kathmandu',
        city: 'Kathmandu',
        latitude: 27.7240,
        longitude: 85.3210,
        phone: '+977-1-4412099',
        isMain: true,
        operatingHours: '07:00 AM - 08:30 PM'
      },
      {
        id: 'branch_himalayan_jhamsikhel',
        merchantId: 'merch_himalayan_organic',
        branchName: 'Jhamsikhel Fresh Hub',
        address: 'Jhamsikhel Road, Lalitpur',
        city: 'Lalitpur',
        latitude: 27.6790,
        longitude: 85.3090,
        phone: '+977-1-5524310',
        isMain: false,
        operatingHours: '07:30 AM - 08:00 PM'
      }
    ]
  },
  {
    id: 'merch_medicare_pharmacy',
    businessName: 'MediCare Emergency & Clinical Supplies',
    businessRegistrationNo: 'NP-DDA-440192',
    category: 'Medical & Healthcare',
    description: '24/7 DDA-registered clinical pharmacy with temperature-controlled cold-chain inventory.',
    trustScore: 99.1,
    verificationStatus: 'verified',
    verifiedAt: '2026-06-10T14:15:00Z',
    contactPhone: '+977-1-4478120',
    contactEmail: 'contact@medicarehealth.np',
    address: 'New Baneshwor Medical Row, Kathmandu',
    city: 'Kathmandu',
    state: 'Bagmati',
    latitude: 27.6915,
    longitude: 85.3420,
    rating: 4.9,
    reviewCount: 210,
    freshnessGuaranteeHours: 1,
    lastInventoryUpdate: new Date(Date.now() - 4 * 60000).toISOString(),
    branches: [
      {
        id: 'branch_medicare_baneshwor',
        merchantId: 'merch_medicare_pharmacy',
        branchName: 'Baneshwor 24/7 Center',
        address: 'New Baneshwor Medical Row, Kathmandu',
        city: 'Kathmandu',
        latitude: 27.6915,
        longitude: 85.3420,
        phone: '+977-1-4478120',
        isMain: true,
        operatingHours: '24 Hours Open'
      }
    ]
  },
  {
    id: 'merch_apex_electronics',
    businessName: 'Apex Circuit & Hardware Component Lab',
    businessRegistrationNo: 'NP-REG-1092837',
    category: 'Electronics & Repair',
    description: 'Engineers & technicians choice for OEM replacement ICs, power modules, sensors & tools.',
    trustScore: 92.5,
    verificationStatus: 'verified',
    verifiedAt: '2026-08-01T11:00:00Z',
    contactPhone: '+977-1-4229988',
    contactEmail: 'tech@apexelectronics.np',
    address: 'New Road Tech Alley, Kathmandu',
    city: 'Kathmandu',
    state: 'Bagmati',
    latitude: 27.7030,
    longitude: 85.3120,
    rating: 4.7,
    reviewCount: 64,
    freshnessGuaranteeHours: 6,
    lastInventoryUpdate: new Date(Date.now() - 45 * 60000).toISOString(),
    branches: [
      {
        id: 'branch_apex_newroad',
        merchantId: 'merch_apex_electronics',
        branchName: 'New Road Main Store',
        address: 'New Road Tech Alley, Kathmandu',
        city: 'Kathmandu',
        latitude: 27.7030,
        longitude: 85.3120,
        phone: '+977-1-4229988',
        isMain: true,
        operatingHours: '09:30 AM - 07:30 PM'
      }
    ]
  },
  {
    id: 'merch_valley_wholesale',
    businessName: 'Valley Mega Provisions & B2B Distribution',
    businessRegistrationNo: 'NP-VAT-50019482',
    category: 'Wholesale & FMCG',
    description: 'Bulk grain, cooking oil, spices, and packaging distributor for restaurants and retail shops.',
    trustScore: 94.0,
    verificationStatus: 'verified',
    verifiedAt: '2026-05-18T08:00:00Z',
    contactPhone: '+977-1-4351280',
    contactEmail: 'wholesale@valleymega.com',
    address: 'Kalanki Industrial Corridor, Kathmandu',
    city: 'Kathmandu',
    state: 'Bagmati',
    latitude: 27.6938,
    longitude: 85.2815,
    rating: 4.6,
    reviewCount: 95,
    freshnessGuaranteeHours: 8,
    lastInventoryUpdate: new Date(Date.now() - 110 * 60000).toISOString(),
    branches: [
      {
        id: 'branch_valley_kalanki',
        merchantId: 'merch_valley_wholesale',
        branchName: 'Kalanki Distribution Depot',
        address: 'Kalanki Industrial Corridor, Kathmandu',
        city: 'Kathmandu',
        latitude: 27.6938,
        longitude: 85.2815,
        phone: '+977-1-4351280',
        isMain: true,
        operatingHours: '06:00 AM - 06:00 PM'
      }
    ]
  },
  {
    id: 'merch_pokhara_tools',
    businessName: 'Annapurna Industrial Tools & Machinery',
    businessRegistrationNo: 'NP-VAT-3091823',
    category: 'Hardware & Construction',
    description: 'Heavy machinery spare parts, welding equipment, and pneumatic tools for western region.',
    trustScore: 89.2,
    verificationStatus: 'verified',
    verifiedAt: '2026-07-12T13:00:00Z',
    contactPhone: '+977-61-532190',
    contactEmail: 'sales@annapurnatools.com',
    address: 'Prithvi Chowk, Pokhara',
    city: 'Pokhara',
    state: 'Gandaki',
    latitude: 28.2096,
    longitude: 83.9856,
    rating: 4.7,
    reviewCount: 42,
    freshnessGuaranteeHours: 12,
    lastInventoryUpdate: new Date(Date.now() - 180 * 60000).toISOString(),
    branches: [
      {
        id: 'branch_pokhara_main',
        merchantId: 'merch_pokhara_tools',
        branchName: 'Pokhara Central Store',
        address: 'Prithvi Chowk, Pokhara',
        city: 'Pokhara',
        latitude: 28.2096,
        longitude: 83.9856,
        phone: '+977-61-532190',
        isMain: true,
        operatingHours: '08:00 AM - 07:00 PM'
      }
    ]
  },
  {
    id: 'merch_everest_bio',
    businessName: 'Everest Bio-Nutrients & Hydroponics',
    businessRegistrationNo: 'NP-REG-9918274',
    category: 'Farm Produce & Agri',
    description: 'New applicant for smart greenhouse microgreens, organic pest deterrents, and bio-nutrients.',
    trustScore: 72.0,
    verificationStatus: 'pending',
    contactPhone: '+977-1-5182903',
    contactEmail: 'info@everestbio.com',
    address: 'Suryabinayak, Bhaktapur',
    city: 'Bhaktapur',
    state: 'Bagmati',
    latitude: 27.6680,
    longitude: 85.4210,
    rating: 4.2,
    reviewCount: 8,
    freshnessGuaranteeHours: 24,
    lastInventoryUpdate: new Date(Date.now() - 360 * 60000).toISOString(),
    branches: [
      {
        id: 'branch_everest_bhaktapur',
        merchantId: 'merch_everest_bio',
        branchName: 'Bhaktapur Greenhouse',
        address: 'Suryabinayak, Bhaktapur',
        city: 'Bhaktapur',
        latitude: 27.6680,
        longitude: 85.4210,
        phone: '+977-1-5182903',
        isMain: true,
        operatingHours: '08:00 AM - 05:00 PM'
      }
    ]
  }
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'prod_opc_cement_50kg',
    merchantId: 'merch_pioneer_hardware',
    branchId: 'branch_pioneer_main',
    categoryId: 'cat_hardware',
    name: 'Shivam 53 Grade OPC Cement (50kg Bag)',
    normalizedName: 'opc cement 53 grade 50kg shivam',
    category: 'Hardware & Construction',
    sku: 'HW-CEM-53-SHV',
    barcode: '8901234567890',
    description: 'High-strength Ordinary Portland Cement (53-Grade) for structural columns, beams, and foundation casting. Fresh batch from factory depot.',
    price: 780,
    wholesalePrice: 720,
    moq: 20,
    unit: 'bag (50kg)',
    stockQuantity: 450,
    lowStockThreshold: 50,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 25 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_pioneer_hardware', 'HW-CEM-53-SHV', 450, '2026-09-18'),
    tags: ['cement', 'opc', 'construction', 'shivam', 'structural', '53 grade'],
    specifications: {
      'Grade': '53 Grade OPC',
      'Standard': 'NS:49 / IS:12269',
      'Weight': '50 kg',
      'Packaging': 'HDPE Moisture Resistant'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 25 * 60000).toISOString()
  },
  {
    id: 'prod_ppc_cement_50kg',
    merchantId: 'merch_pioneer_hardware',
    branchId: 'branch_pioneer_main',
    categoryId: 'cat_hardware',
    name: 'Hetauda PPC Premium Cement (50kg Bag)',
    normalizedName: 'ppc cement 50kg hetauda portland pozzolana',
    category: 'Hardware & Construction',
    sku: 'HW-CEM-PPC-HET',
    description: 'Portland Pozzolana Cement ideal for masonry plastering, brick laying, and non-structural water-resistant concrete.',
    price: 680,
    wholesalePrice: 630,
    moq: 25,
    unit: 'bag (50kg)',
    stockQuantity: 18,
    lowStockThreshold: 30,
    stockStatus: 'low_stock',
    freshnessDate: new Date(Date.now() - 40 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_pioneer_hardware', 'HW-CEM-PPC-HET', 18, '2026-09-18'),
    tags: ['cement', 'ppc', 'construction', 'plastering', 'hetauda'],
    specifications: {
      'Type': 'PPC (Portland Pozzolana)',
      'Standard': 'NS:385',
      'Setting Time': '30 min initial',
      'Weight': '50 kg'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 40 * 60000).toISOString()
  },
  {
    id: 'prod_rebar_12mm',
    merchantId: 'merch_pioneer_hardware',
    branchId: 'branch_pioneer_balkhu',
    categoryId: 'cat_hardware',
    name: 'Jagdamba Fe 500D TMT Steel Rebar (12mm)',
    normalizedName: 'rebar tmt steel rod 12mm fe 500d jagdamba',
    category: 'Hardware & Construction',
    sku: 'HW-STEEL-12MM-JAG',
    description: 'High-ductility seismic-resistant thermo-mechanically treated bar. Full test certificate included.',
    price: 98,
    wholesalePrice: 91,
    moq: 100,
    unit: 'kg',
    stockQuantity: 5200,
    lowStockThreshold: 500,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 60 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_pioneer_hardware', 'HW-STEEL-12MM-JAG', 5200, '2026-09-18'),
    tags: ['rebar', 'steel', 'tmt', '12mm', 'jagdamba', 'iron', 'construction'],
    specifications: {
      'Grade': 'Fe 500D (Seismic Resistant)',
      'Diameter': '12 mm',
      'Length': '12 meters / piece',
      'Elongation': '> 16%'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 60 * 60000).toISOString()
  },
  {
    id: 'prod_makita_rotary_drill',
    merchantId: 'merch_pioneer_hardware',
    branchId: 'branch_pioneer_main',
    categoryId: 'cat_hardware',
    name: 'Makita HR2470 24mm Rotary Hammer Drill (780W)',
    normalizedName: 'makita rotary hammer drill hr2470 24mm 780w power tool',
    category: 'Hardware & Construction',
    sku: 'HW-TOOL-MAK-HR2470',
    description: 'Heavy duty 3-mode SDS-Plus hammer drill for concrete drilling, chiseling and rotary hammering.',
    price: 14500,
    wholesalePrice: 13200,
    moq: 2,
    unit: 'unit',
    stockQuantity: 6,
    lowStockThreshold: 2,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 120 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_pioneer_hardware', 'HW-TOOL-MAK-HR2470', 6, '2026-09-18'),
    tags: ['drill', 'hammer', 'makita', 'power tools', 'concrete', 'sds'],
    specifications: {
      'Power Input': '780 Watts',
      'Impact Energy': '2.4 Joules',
      'Drilling Capacity': 'Concrete 24mm, Steel 13mm',
      'Warranty': '1 Year Official'
    },
    isActive: true,
    createdAt: '2026-08-05T00:00:00Z',
    updatedAt: new Date(Date.now() - 120 * 60000).toISOString()
  },
  {
    id: 'prod_bosch_hammer_drill',
    merchantId: 'merch_pokhara_tools',
    branchId: 'branch_pokhara_main',
    categoryId: 'cat_hardware',
    name: 'Bosch GBH 2-26 DRE Professional Rotary Hammer',
    normalizedName: 'bosch rotary hammer drill gbh 2-26 dre power tool',
    category: 'Hardware & Construction',
    sku: 'HW-TOOL-BOS-226',
    description: 'Fast all-rounder hammer drill with 800W motor, rotation stop for chiseling, and ball grommet for cable protection.',
    price: 15200,
    wholesalePrice: 13900,
    moq: 2,
    unit: 'unit',
    stockQuantity: 9,
    lowStockThreshold: 2,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 75 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_pokhara_tools', 'HW-TOOL-BOS-226', 9, '2026-09-18'),
    tags: ['drill', 'bosch', 'power tools', 'hammer', 'chiseling'],
    specifications: {
      'Power Input': '800 Watts',
      'Impact Rate': '0-4000 bpm',
      'Weight': '2.7 kg'
    },
    isActive: true,
    createdAt: '2026-08-10T00:00:00Z',
    updatedAt: new Date(Date.now() - 75 * 60000).toISOString()
  },
  {
    id: 'prod_paracetamol_500mg',
    merchantId: 'merch_medicare_pharmacy',
    branchId: 'branch_medicare_baneshwor',
    categoryId: 'cat_pharmacy',
    name: 'Niko Paracetamol 500mg IP (Strip of 10 Tablets)',
    normalizedName: 'paracetamol 500mg niko cetamol fever pain relief tablet',
    category: 'Medical & Healthcare',
    sku: 'MED-PARA-500-NKO',
    barcode: '8904018273615',
    description: 'Pure Paracetamol 500mg analgesic & antipyretic for fever, headache, body ache. GMP certified.',
    price: 25,
    wholesalePrice: 18,
    moq: 50,
    unit: 'strip (10 tabs)',
    stockQuantity: 840,
    lowStockThreshold: 100,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 10 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_medicare_pharmacy', 'MED-PARA-500-NKO', 840, '2026-09-18'),
    tags: ['paracetamol', 'fever', 'medicine', 'painkiller', 'tablets', 'cetamol'],
    specifications: {
      'Dosage': '500 mg IP',
      'Batch No': 'NK-2609-P4',
      'Expiry Date': '2028-11-30',
      'Manufacturer': 'Nepal Pharmaceuticals Lab'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 10 * 60000).toISOString()
  },
  {
    id: 'prod_n95_respirator_box',
    merchantId: 'merch_medicare_pharmacy',
    branchId: 'branch_medicare_baneshwor',
    categoryId: 'cat_pharmacy',
    name: '3M 8210 N95 Particulate Respirator (Box of 20)',
    normalizedName: '3m 8210 n95 medical mask respirator surgical box 20',
    category: 'Medical & Healthcare',
    sku: 'MED-MASK-3M-8210',
    description: 'NIOSH-approved N95 particulate filtration respirator with adjustable noseclip and cushioning foam.',
    price: 1850,
    wholesalePrice: 1550,
    moq: 5,
    unit: 'box (20 pcs)',
    stockQuantity: 0,
    lowStockThreshold: 10,
    stockStatus: 'out_of_stock',
    freshnessDate: new Date(Date.now() - 300 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_medicare_pharmacy', 'MED-MASK-3M-8210', 0, '2026-09-18'),
    tags: ['n95', 'mask', '3m', 'respirator', 'medical', 'ppe'],
    specifications: {
      'Filtration': '95% @ 0.3 micron',
      'Standard': 'NIOSH N95',
      'Quantity': '20 Masks / Box'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 300 * 60000).toISOString()
  },
  {
    id: 'prod_surgical_mask_box',
    merchantId: 'merch_medicare_pharmacy',
    branchId: 'branch_medicare_baneshwor',
    categoryId: 'cat_pharmacy',
    name: '3-Ply Medical Surgical Face Mask (Box of 50)',
    normalizedName: '3 ply surgical face mask meltblown box 50 certified',
    category: 'Medical & Healthcare',
    sku: 'MED-MASK-3PLY-50',
    description: 'High bacterial filtration efficiency (BFE > 99%) 3-ply ultrasonic welded surgical mask with soft earloops.',
    price: 350,
    wholesalePrice: 280,
    moq: 10,
    unit: 'box (50 pcs)',
    stockQuantity: 120,
    lowStockThreshold: 20,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 15 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_medicare_pharmacy', 'MED-MASK-3PLY-50', 120, '2026-09-18'),
    tags: ['mask', 'surgical', '3ply', 'face mask', 'ppe', 'medical'],
    specifications: {
      'BFE': '> 99%',
      'Ply': '3 Ply (Meltblown Filter Layer)',
      'Quantity': '50 Masks / Box'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 15 * 60000).toISOString()
  },
  {
    id: 'prod_pulse_oximeter',
    merchantId: 'merch_medicare_pharmacy',
    branchId: 'branch_medicare_baneshwor',
    categoryId: 'cat_pharmacy',
    name: 'Beurer PO 30 Fingertip Pulse Oximeter & SpO2 Monitor',
    normalizedName: 'pulse oximeter beurer po 30 spo2 heart rate monitor fingertip',
    category: 'Medical & Healthcare',
    sku: 'MED-DEV-BEU-PO30',
    description: 'German-engineered fingertip pulse oximeter for SpO2 oxygen saturation and heart pulse rate with OLED display.',
    price: 3200,
    wholesalePrice: 2750,
    moq: 5,
    unit: 'unit',
    stockQuantity: 15,
    lowStockThreshold: 3,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 45 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_medicare_pharmacy', 'MED-DEV-BEU-PO30', 15, '2026-09-18'),
    tags: ['oximeter', 'spo2', 'medical device', 'oxygen', 'beurer', 'pulse'],
    specifications: {
      'Display': 'Color OLED 4-view',
      'Accuracy': '+/- 2% SpO2',
      'Power': '2x AAA Batteries (Included)'
    },
    isActive: true,
    createdAt: '2026-08-10T00:00:00Z',
    updatedAt: new Date(Date.now() - 45 * 60000).toISOString()
  },
  {
    id: 'prod_mustard_oil_coldpressed',
    merchantId: 'merch_himalayan_organic',
    branchId: 'branch_himalayan_lazimpat',
    categoryId: 'cat_agriculture',
    name: 'Pure Cold-Pressed Himalayan Mustard Oil (5 Litre Tin)',
    normalizedName: 'mustard oil cold pressed organic tite tori ko tel 5 litre',
    category: 'Farm Produce & Agri',
    sku: 'AGR-OIL-MUST-5L',
    description: 'Traditional wood-churned (Kolhu) cold-pressed yellow mustard oil. High pungent natural aroma with zero preservatives.',
    price: 1950,
    wholesalePrice: 1750,
    moq: 4,
    unit: 'tin (5 Litres)',
    stockQuantity: 42,
    lowStockThreshold: 10,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 12 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_himalayan_organic', 'AGR-OIL-MUST-5L', 42, '2026-09-18'),
    tags: ['mustard oil', 'cold pressed', 'organic', 'tori tel', 'cooking oil', 'agri'],
    specifications: {
      'Processing': 'Cold-Pressed Wood Churn',
      'Volume': '5.0 Litres',
      'Purity': '100% Raw Unfiltered',
      'Origin': 'Chitwan Organic Farm'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 12 * 60000).toISOString()
  },
  {
    id: 'prod_jumla_organic_apples',
    merchantId: 'merch_himalayan_organic',
    branchId: 'branch_himalayan_jhamsikhel',
    categoryId: 'cat_agriculture',
    name: 'Jumla High-Altitude Royal Delicious Apples (10kg Crate)',
    normalizedName: 'jumla organic apple royal delicious high altitude crate 10kg',
    category: 'Farm Produce & Agri',
    sku: 'AGR-FRUIT-JUM-APP',
    description: 'Pesticide-free crisp sweet organic apples harvested from 2,500m elevation in Jumla valley.',
    price: 2400,
    wholesalePrice: 2100,
    moq: 5,
    unit: 'crate (10kg)',
    stockQuantity: 28,
    lowStockThreshold: 5,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 18 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_himalayan_organic', 'AGR-FRUIT-JUM-APP', 28, '2026-09-18'),
    tags: ['apples', 'jumla', 'organic', 'fruits', 'fresh produce', 'local'],
    specifications: {
      'Variety': 'Royal Delicious',
      'Origin': 'Jumla, Karnali',
      'Weight': '10 kg Net',
      'Harvest Date': 'Sept 2026'
    },
    isActive: true,
    createdAt: '2026-08-05T00:00:00Z',
    updatedAt: new Date(Date.now() - 18 * 60000).toISOString()
  },
  {
    id: 'prod_wild_cliff_honey',
    merchantId: 'merch_himalayan_organic',
    branchId: 'branch_himalayan_lazimpat',
    categoryId: 'cat_agriculture',
    name: 'Raw Himalayan Wild Cliff Honey (1kg Jar)',
    normalizedName: 'raw himalayan wild cliff honey maha organic 1kg pure',
    category: 'Farm Produce & Agri',
    sku: 'AGR-HON-CLIFF-1KG',
    description: 'Unpasteurized mountain cliff honey collected by indigenous Gurung honey hunters. Rich in enzymes and antioxidants.',
    price: 1800,
    wholesalePrice: 1550,
    moq: 6,
    unit: 'glass jar (1kg)',
    stockQuantity: 19,
    lowStockThreshold: 5,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 35 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_himalayan_organic', 'AGR-HON-CLIFF-1KG', 19, '2026-09-18'),
    tags: ['honey', 'cliff honey', 'wild honey', 'organic', 'raw honey', 'maha'],
    specifications: {
      'Purity': '100% Raw Unfiltered',
      'Moisture Content': '< 17%',
      'Weight': '1.0 kg'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 35 * 60000).toISOString()
  },
  {
    id: 'prod_esp32_wroom_module',
    merchantId: 'merch_apex_electronics',
    branchId: 'branch_apex_newroad',
    categoryId: 'cat_electronics',
    name: 'Espressif ESP32-WROOM-32D WiFi + BLE Dev Board',
    normalizedName: 'esp32 wroom 32d microcontroller wifi bluetooth iot dev board',
    category: 'Electronics & Repair',
    sku: 'ELC-MCU-ESP32-DEV',
    description: 'Dual-core Xtensa 32-bit LX6 MCU with built-in Wi-Fi and Bluetooth LE. CP2102 USB interface with Type-C connector.',
    price: 650,
    wholesalePrice: 520,
    moq: 10,
    unit: 'pcs',
    stockQuantity: 145,
    lowStockThreshold: 20,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 50 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_apex_electronics', 'ELC-MCU-ESP32-DEV', 145, '2026-09-18'),
    tags: ['esp32', 'iot', 'microcontroller', 'arduino', 'wifi', 'bluetooth', 'electronics'],
    specifications: {
      'MCU': 'ESP32-D0WDQ6 Dual Core 240MHz',
      'Flash Memory': '4MB SPI Flash',
      'Connector': 'USB Type-C',
      'Operating Voltage': '3.3V / 5V'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 50 * 60000).toISOString()
  },
  {
    id: 'prod_soldering_station_936d',
    merchantId: 'merch_apex_electronics',
    branchId: 'branch_apex_newroad',
    categoryId: 'cat_electronics',
    name: 'Quick 936D+ Digital ESD Safe Soldering Station (60W)',
    normalizedName: 'soldering iron station digital temperature esd quick 936d repair',
    category: 'Electronics & Repair',
    sku: 'ELC-TOOL-SLD-936D',
    description: 'Precise PID temperature-controlled ceramic heating soldering station with LCD display and ESD safe grounding.',
    price: 4800,
    wholesalePrice: 4200,
    moq: 2,
    unit: 'unit',
    stockQuantity: 8,
    lowStockThreshold: 2,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 65 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_apex_electronics', 'ELC-TOOL-SLD-936D', 8, '2026-09-18'),
    tags: ['soldering', 'iron', 'electronics repair', 'tools', 'esd'],
    specifications: {
      'Power': '60 Watts',
      'Temperature Range': '200°C - 480°C',
      'Heating Element': 'Imported Ceramic Core'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 65 * 60000).toISOString()
  },
  {
    id: 'prod_basmati_rice_25kg',
    merchantId: 'merch_valley_wholesale',
    branchId: 'branch_valley_kalanki',
    categoryId: 'cat_wholesale',
    name: 'Royal Heritage Aged Long-Grain Basmati Rice (25kg Bag)',
    normalizedName: 'basmati rice 25kg royal heritage aged long grain bulk food',
    category: 'Wholesale & FMCG',
    sku: 'FMCG-RICE-BAS-25KG',
    description: '2-year aged XXL premium long-grain aromatic basmati rice for restaurants, catering, and retail grocery stores.',
    price: 3600,
    wholesalePrice: 3250,
    moq: 10,
    unit: 'bag (25kg)',
    stockQuantity: 320,
    lowStockThreshold: 40,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 90 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_valley_wholesale', 'FMCG-RICE-BAS-25KG', 320, '2026-09-18'),
    tags: ['rice', 'basmati', 'wholesale', 'provisions', 'food', 'bulk', '25kg'],
    specifications: {
      'Grain Length': '8.3 mm Average Cooked',
      'Aging': '24 Months Matured',
      'Packaging': 'Woven Polypropylene 25kg'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 90 * 60000).toISOString()
  },
  {
    id: 'prod_sunflower_oil_15l',
    merchantId: 'merch_valley_wholesale',
    branchId: 'branch_valley_kalanki',
    categoryId: 'cat_wholesale',
    name: 'Fortune Refined Sunflower Oil (15 Litre Commercial Jar)',
    normalizedName: 'sunflower oil 15 litre refined cooking fortune bulk restaurant',
    category: 'Wholesale & FMCG',
    sku: 'FMCG-OIL-SUN-15L',
    description: 'Triple-refined vitamin enriched light sunflower oil with high smoke point for commercial kitchens and frying.',
    price: 4350,
    wholesalePrice: 3980,
    moq: 5,
    unit: 'jar (15 Litres)',
    stockQuantity: 110,
    lowStockThreshold: 20,
    stockStatus: 'in_stock',
    freshnessDate: new Date(Date.now() - 110 * 60000).toISOString(),
    freshnessHash: generateFreshnessHashSync('merch_valley_wholesale', 'FMCG-OIL-SUN-15L', 110, '2026-09-18'),
    tags: ['sunflower oil', 'cooking oil', 'wholesale', 'bulk', 'restaurant', '15l'],
    specifications: {
      'Enrichment': 'Vitamin A & D',
      'Smoke Point': '232°C',
      'Volume': '15.0 Litres'
    },
    isActive: true,
    createdAt: '2026-08-01T00:00:00Z',
    updatedAt: new Date(Date.now() - 110 * 60000).toISOString()
  }
];

export const INITIAL_DEMAND_SIGNALS: DemandSignal[] = [
  {
    id: 'sig_demand_ppc_cement',
    queryTerm: 'ppc cement 50kg bag',
    category: 'Hardware & Construction',
    searchCount: 384,
    unmetCount: 142,
    estimatedDemandValue: 345000,
    locationCluster: 'Lalitpur / Baneshwor',
    trendDirection: 'explosive',
    detectedAt: new Date(Date.now() - 35 * 60000).toISOString(),
    sampleItemMatch: 'Hetauda PPC Premium Cement (50kg Bag)'
  },
  {
    id: 'sig_demand_n95_respirator',
    queryTerm: '3M N95 medical masks box 20',
    category: 'Medical & Healthcare',
    searchCount: 290,
    unmetCount: 185,
    estimatedDemandValue: 120000,
    locationCluster: 'Kathmandu Metro / Baneshwor',
    trendDirection: 'rising',
    detectedAt: new Date(Date.now() - 50 * 60000).toISOString(),
    sampleItemMatch: '3M 8210 N95 Particulate Respirator (Box of 20)'
  },
  {
    id: 'sig_demand_esp32_c3',
    queryTerm: 'esp32 c3 mini dev board usb c',
    category: 'Electronics & Repair',
    searchCount: 165,
    unmetCount: 94,
    estimatedDemandValue: 85000,
    locationCluster: 'New Road / Patan',
    trendDirection: 'rising',
    detectedAt: new Date(Date.now() - 90 * 60000).toISOString(),
    sampleItemMatch: 'Espressif ESP32-WROOM-32D WiFi Dev Board'
  },
  {
    id: 'sig_demand_organic_kiwi',
    queryTerm: 'organic kiwi fruit crate 5kg',
    category: 'Farm Produce & Agri',
    searchCount: 210,
    unmetCount: 110,
    estimatedDemandValue: 160000,
    locationCluster: 'Jhamsikhel / Lazimpat',
    trendDirection: 'rising',
    detectedAt: new Date(Date.now() - 140 * 60000).toISOString(),
    sampleItemMatch: 'Jumla High-Altitude Royal Delicious Apples'
  }
];

export const INITIAL_STOCKOUT_REQUESTS: StockoutRequest[] = [
  {
    id: 'req_stockout_01',
    customerName: 'Suman Shrestha (Civil Contractor)',
    customerContact: '+977-9841829301',
    queryText: 'Urgent 80 bags of PPC Plastering Cement for site in Balkhu',
    category: 'Hardware & Construction',
    targetQuantity: 80,
    locationCity: 'Kathmandu',
    maxRadiusKm: 10,
    status: 'seeking',
    notes: 'Need delivery by tomorrow morning or immediate pickup.',
    createdAt: new Date(Date.now() - 45 * 60000).toISOString()
  },
  {
    id: 'req_stockout_02',
    customerName: 'Dr. Aarav Koirala (Clinic Admin)',
    customerContact: '+977-9801928472',
    queryText: '10 Boxes 3M 8210 N95 Respirators for dental surgery wing',
    category: 'Medical & Healthcare',
    targetQuantity: 10,
    locationCity: 'Kathmandu',
    maxRadiusKm: 15,
    status: 'seeking',
    notes: 'Must be authentic NIOSH certified with verifiable lot code.',
    createdAt: new Date(Date.now() - 75 * 60000).toISOString()
  }
];

export const INITIAL_RESERVATIONS: Reservation[] = [
  {
    id: 'res_sample_01',
    productId: 'prod_opc_cement_50kg',
    productName: 'Shivam 53 Grade OPC Cement (50kg Bag)',
    merchantId: 'merch_pioneer_hardware',
    merchantName: 'Pioneer Construction & Hardware Depot',
    branchId: 'branch_pioneer_main',
    branchName: 'Lalitpur Central Yard',
    customerName: 'Bikash Mahat',
    customerPhone: '+977-9851092834',
    customerEmail: 'bikash.m@gmail.com',
    quantity: 25,
    unitPrice: 720,
    totalPrice: 18000,
    status: 'active',
    pickupCode: 'STK-7A9-V2X',
    fulfillmentType: 'pickup',
    expiresAt: new Date(Date.now() + 3 * 3600000).toISOString(),
    createdAt: new Date(Date.now() - 30 * 60000).toISOString()
  }
];

export const INITIAL_RFQS: RFQInquiry[] = [
  {
    id: 'rfq_sample_01',
    productId: 'prod_basmati_rice_25kg',
    productName: 'Royal Heritage Aged Long-Grain Basmati Rice (25kg Bag)',
    merchantId: 'merch_valley_wholesale',
    merchantName: 'Valley Mega Provisions & B2B Distribution',
    customerName: 'Heritage Hotel & Banquet',
    customerEmail: 'purchasing@heritagehotel.np',
    customerPhone: '+977-1-4438290',
    requestedQuantity: 50,
    targetPrice: 3100,
    message: 'We require monthly recurring supply of 50 bags. Can you offer bulk tier discount and door delivery?',
    status: 'pending',
    createdAt: new Date(Date.now() - 120 * 60000).toISOString(),
    updatedAt: new Date(Date.now() - 120 * 60000).toISOString()
  }
];
